### ISSUE TITLE
add some details to the ReadME file

### ISSUE THREAD

**Issue by ThanushaMandala** [ThanushaMandala/weatherApp#1]
this is a simple weatherApp which takes a cityName as input and makes an API call to fetch the weather. 

Add steps on how to run the weatherApp, and any more details around API being consumed.

**Comment by sirish123** [comment]
could u assign me this!

**Comment by saakshi002** [comment]
Hi @ThanushaMandala , can you assign me this task?

**Comment by ThanushaMandala** [comment]
done @saakshi002

**Comment by LeMinhMan2809** [comment]
Hi @ThanushaMandala, can you please assign me this task?

**Comment by ThanushaMandala** [comment]
@saakshi002 let me know if u are not actively working on this issue so that I can reassign.

**Comment by saakshi002** [comment]
Yes, I am working on it.
