### ISSUE TITLE
Add a toggle button for light and dark modes

### ISSUE THREAD

**Issue by ThanushaMandala** [ThanushaMandala/weatherApp#14]
Add a toggle button at the top for the user to choose between the light and dark modes as per their choice

**Comment by amanpandey3956** [comment]
@ThanushaMandala can you assign this to me ?? would love to work on this.

**Comment by ThanushaMandala** [comment]
done @amanpandey3956

**Comment by ThanushaMandala** [comment]
#48 resolves this issue
