### ISSUE TITLE
Add some styling to the data returned for a city entered

### ISSUE THREAD

**Issue by ThanushaMandala** [ThanushaMandala/weatherApp#16]
Add some css styles to the data returned that is displayed in the weatherApp, any styling which improvises the current state.

**Comment by ankitkumar0622** [comment]
Hi @ThanushaMandala , can you assign me this task.

**Comment by ThanushaMandala** [comment]
@ankitkumar0622 done!

**Comment by AviGawande** [comment]
hello @ThanushaMandala  would like to work on this repo .

**Comment by ThanushaMandala** [comment]
@ankitkumar0622 if not actively working on this issue pls let me know so that I can reassign.

**Comment by ThanushaMandala** [comment]
@AviGawande feel free to raise a PR, and will assign this issue to you.

**Comment by Hantaro171902** [comment]
Hi, I want to try this, can you send me the repo ?

**Comment by banjaneyulu** [comment]
@ThanushaMandala can you assign this to me

**Comment by Madara909** [comment]
please assign this issue to me
