### ISSUE TITLE
Add more weather data: fetch and display additional weather data such as wind speed

### ISSUE THREAD

**Issue by ThanushaMandala** [ThanushaMandala/weatherApp#5]
from the API response fetch the parameter **wind_spd** and display the value as wind speed to the end user

**Comment by supunvindula** [comment]
Hi @ThanushaMandala ,
I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by ThanushaMandala** [comment]
@supunvindula assigned

**Comment by supunvindula** [comment]
Hi I have created the [PR](https://github.com/ThanushaMandala/weatherApp/pull/37)
