### ISSUE TITLE
Add more weather data: fetch and display additional weather data such as humidity

### ISSUE THREAD

**Issue by ThanushaMandala** [ThanushaMandala/weatherApp#6]
from the API response fetch the parameter **rh** and display the value as humidity to the end user

**Comment by supunvindula** [comment]
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by ThanushaMandala** [comment]
@supunvindula assigned!

**Comment by ThanushaMandala** [comment]
sure @gouravjoshi21, @supunvindula feel free to pickup any other open tasks as a PR has already been raised to fix this issue

**Comment by supunvindula** [comment]
Humidity was there. But the unit of humidity was not. I have changed that. [Click here to access PR](https://github.com/ThanushaMandala/weatherApp/pull/38)
