### ISSUE TITLE
Add more weather data: fetch and display additional weather data such as pressure

### ISSUE THREAD

**Issue by ThanushaMandala** [ThanushaMandala/weatherApp#7]
from the API response fetch the parameter **pres** and display the value as pressure to the end user

**Comment by soumytiwari** [comment]
I suppose.. your 7th, 6th and 5th issues are doing same work, for different parameters. 
Why this? I suppose, you accideentally did something
Why "wind speed" is being represented by 3 parameters?
Could you explain??
Well.. I would like to work on them.

(also, these api calls.. you want to be done from where??)

**Comment by ThanushaMandala** [comment]
hi @soumytiwari updated the description, hope it is clear now. this issue focusses on fetching the **pres** parameter from API response and display it to the customer.

the API call is already being made in index.js file, u just need to extract this param and then display.

let me know if you have more queries

**Comment by soumytiwari** [comment]
okay sure, thanks 😊
