### ISSUE TITLE
Add a background image which is relevant to the weather app

### ISSUE THREAD

**Issue by ThanushaMandala** [ThanushaMandala/weatherApp#9]
Add a background image to the app to make it more visually appealing. You can choose an image that is related to weather, Example you can chose a picture of clouds.

**Comment by the-shivam-gupta** [comment]
assign it to me.

**Comment by ThanushaMandala** [comment]
assigned @the-shivam-gupta

**Comment by AviGawande** [comment]
@ThanushaMandala if issue is still open to work then i would like  to work on it.

**Comment by ThanushaMandala** [comment]
@AviGawande PR has already been raised by @the-shivam-gupta just minor comments pending.

**Comment by ThanushaMandala** [comment]
PR #32 resolves this issue
